name: Test docker file

on: [push, pull_request]

env:
  TEST_TAG: texasaggie97/texasaggie97/hover-dns-updater:test
  LATEST_TAG: texasaggie97/texasaggie97/hover-dns-updater:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configure poetry so we can generate a requirements file
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: "1.5.1"

      - name: Generate requirements.txt file
        run: |
          poetry export -f requirements.txt > requirements.txt --without-hashes

      - name: Generate requirements-dev.txt file
        run: |
          poetry export -f requirements.txt > requirements-dev.txt --without-hashes --with=dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
          target: test

